server:
  domain: localhost
  port: 12309
  name: Terrorsaru-Web Server
dataSource:
  host: localhost
  port: 3306
  userName: root
  password: root
  databaseName: ancient_article
  charset: utf8
  maxIdleConnections: 10
  maxOpenConnections: 100