basePath: /v1
host: 172.16.21.207:12309
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Terrorsaur-鸵鸟勇士
  version: "1.0"
paths:
  /api/rattrap/ancient-article/author/{authorId:
    get:
      consumes:
      - application/json
      description: 获取Author信息列表
      produces:
      - application/json
      summary: Author信息列表
swagger: "2.0"
